[workspace]
resolver = "2"  # See: https://doc.rust-lang.org/cargo/reference/resolver.html#resolver-versions

members = [
    "Chapter02/guessing_game",
    "Chapter05/rectangle",
    "Chapter06/enums",
    "Chapter07/restaurant",
]
